spring:
  sql.init.mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL_CUSTOMIZE}
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: cbfZjNawhGCMkqA7yuQyMT7XmepLvW1T123avd
  token-expires-after-days: 14
